### ISSUE TITLE
[Question] How to handle events?

### ISSUE THREAD

**Issue by Grimeton** [powerman/perl-JSON-RPC2#5]
Hi,

some JSON RPC servers have something like an event model. You can subscribe to certain events and when something occurs you're sent an event object. The "id" of the object is always "NULL" and the type is always "event".  I'm actually using this together with WebSockets... (AnyEvent::WebSocket::Client).

Looking at the source of the response() sub, I can see that an "id" of value "NULL" is always sorted out. Is there an event handling that I just cannot see, or is it just not implemented?

Don't get me wrong here, I'm fine if it's not implemented, I'm just asking before reinventing the wheel.

KR,

G.

**Comment by powerman** [comment]
Sorry for delay, was busy working.

I believe this is implemented. These "events" are called ["notifications"](https://www.jsonrpc.org/specification#notification). And the thing is, I suppose you're looking at them from the wrong side: Server can't send them, the "sender" side in JSON-RPC is considered a Client. So, you can use Client to send them (using `$client->notify()`), and Server will be able to receive them (but not respond to them, that's the reason of code you're referring to).

In practice this usually means your both sides of connection may need to have both Client and Server roles: e.g. browser is acting as a Client when it sends RPC **Request** to an API service, and same browser is acting as a Server when it receives RPC **Notification** (events) from an API service. API service, in turn, also act as a Server when it needs to process RPC **Request** from a browser, and act as a Client when it needs to stream **Notification** (events) to a browser.
